version: '3.7'
 
services:
  openmrs:
    container_name: smart-openmrs
    hostname: smart-openmrs
    build: ./docker/openmrs-server
    restart: unless-stopped
    env_file:
        - ./openmrs-server.env
    volumes:
      - ./distribution:/openmrs/distribution
      - openmrs-data:/openmrs/data
    networks:
      - sedish
    ports:
      - 8003:8000 # Debug
      - 8093:8080

  keycloak:
    restart: unless-stopped
    image: quay.io/keycloak/keycloak:latest
    entrypoint: [ "/opt/jboss/tools/docker-entrypoint.sh", "--debug", "*:9000" ]
    ports:
      - "8088:8080"
      - "1056:9000"
    environment:
      DB_VENDOR: mysql
      DB_ADDR: mysql
      DB_PORT: ${MYSQL_PORT:-3306}
      DB_DATABASE: ${MYSQL_KEYCLOAK_DATABASE:-keycloak}
      DB_USER: ${MYSQL_KEYCLOAK_USER:-keycloak}
      DB_PASSWORD: ${MYSQL_KEYCLOAK_PASSWORD:-password}
      KEYCLOAK_USER: ${KEYCLOAK_USER:-admin}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD:-Admin123}
    healthcheck:
      test: "curl -sSL http://localhost:8080/auth"
    volumes:
      - type: bind
        source: ./openmrs-keycloak-1.0.0-SNAPSHOT.ear
        target: /opt/jboss/keycloak/standalone/deployments/openmrs-keycloak.ear
      - type: bind
        source: ./openmrs-keycloak-smart-authentication-1.0.0-SNAPSHOT.ear
        target: /opt/jboss/keycloak/standalone/deployments/openmrs-keycloak-smart-authentication.ear
 
volumes:
   mysql-data:
   openmrs-data:

networks:
  sedish:
    external:
      name: sedish-haitiorg_sedish